# برنامه برای گرفتن و ذخیره مشخصات شخصی

first_name = "mohammad"
print(first_name)
age=  int("25") 
print(age)



first_name= "Mohammad"
last_name= "Ali"
age= "30"
is_male= True 
height= "180"            #centimeter 
weight= "70"             #kilogram
eye_color= "black"
birthday= "1995"
country= "Iran"
birth_city= "Tehran"
country_of_residence= "U.S"
mother_tongue= "persian"
job= "doctor"
favorite_sport= "football"


print("first name:", first_name)
print("last name:", last_name)
print("age:", age)
print("height:", height)
print("weight:", weight)
print("eye color:", eye_color)
print("birthday:", birthday)
print("country:", country)
print("birth city:", birth_city)
print("contry of residence:", country_of_residence)
print("mother tongue:", mother_tongue)
print("job:", job)
print("favorite sport:", favorite_sport)





